#!/usr/bin/env python
# -*- coding: utf-8 -*-

import xml.etree.cElementTree as ET

OSM_FILE = "pune_india.osm"
NODES_PATH = "nodes.csv"
NODE_TAGS_PATH = "nodes_tags.csv"
WAYS_PATH = "ways.csv"
WAY_NODES_PATH = "ways_nodes.csv"
WAY_TAGS_PATH = "ways_tags.csv"

def read_osm_file():
    return ET.iterparse(OSM_FILE, events=('start','end'))

def get_all_top_level_tags():
    all_top_level_tags = {}
    context = read_osm_file()
    _, root = next(context)
    for event, elem in context:
        tag = elem.tag
        if event == 'start':
            if tag in all_top_level_tags:
                all_top_level_tags[tag] += 1
            else:
                all_top_level_tags[tag] = 1
    return all_top_level_tags

def audit_data():
    print "I will audit all your data to make more sense out of it and clean it aswell!"
    context = read_osm_file()
    _,root = next(context)

if __name__ == '__main__':
    #print "1. get all to level tags"
    #all_top_level_tags = get_all_top_level_tags()
    #print all_top_level_tags
    print "2. audit the data"
    audit_data()
